function createfigure(XData1, YData1, Y1, Parent1)
%CREATEFIGURE(XDATA1, YDATA1, Y1, PARENT1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  Y1:  stairs y
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 29-Mar-2018 22:49:30

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('ColorOrder',...
    [1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863],...
    'Tag','DisplayAxes1_RealMag');
hold(axes1,'on');

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','ciągły','Tag','DisplayLine1',...
    'Color',[1 1 0.0666666666666667]);

% Create stairs
stairs(XData1,Y1,'DisplayName','dyskretny','Tag','DisplayLine1',...
    'Color',[0.0745098039215686 0.623529411764706 1]);

% Create xlabel
xlabel(' ','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0324994258067054 0.292494832260349]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'GridAlpha',0.4,...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'OuterPosition',[0 0 1 1],'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',...
    'TextColor',[0.882062358925529 0.882062358925529 0.882062358925529],...
    'Position',[539.460366278241 408.16666929823 105.999998062849 38.499998986721],...
    'Interpreter','none',...
    'FontSize',10,...
    'EdgeColor',[0.882062358925529 0.882062358925529 0.882062358925529]);

% Create text
text('Parent',Parent1,'Tag','TimeOffsetStatus','Units','pixels',...
    'VerticalAlignment','bottom',...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

